.

diff --git a/bin/awa-setup b/bin/awa-setup
--- a/bin/awa-setup
+++ b/bin/awa-setup
@@ -1,19 +1,20 @@
-#!/bin/bash
+#!/usr/bin/env bash
+set -e
 
-root=$( realpath "`dirname $BASH_SOURCE`/../" )
+root=$(realpath "$(dirname $BASH_SOURCE)/../")
 source "$root/bin/include.sh"
 
 pushd "$root"
 echo "awa path: $root"
 
-venv_setting="`setting virtual_env`"
+venv_setting="$(setting virtual_env)"
 venv_default="$root/.awa-env"
 venv=${venv_setting:=$venv_default}
 venv_activate="$venv/bin/activate"
 python -mvenv "$venv" --clear --copies
 source $venv_activate
 
-pyver=`python -V | cut -d ' ' -f 2`
+pyver=$(python -V | cut -d ' ' -f 2)
 echo "virtual env: $venv (python $pyver)"
 
 echo -n "dependencies: "
@@ -32,8 +33,11 @@ npm install --quiet
 
 echo "complete!"
 
-djver=`pip show django | grep Version | cut -d ' ' -f 2`
+djver=$(pip show django | grep Version | cut -d ' ' -f 2)
 echo "django version: $djver"
+
+echo -n "integrity check: "
+./manage.py check -v 0 && echo "ok" || echo "fail" && ./manage.py check -v 2
 
 echo -n "maintenance: "
 
@@ -41,10 +45,13 @@ echo -n "database "
 ./manage.py migrate --noinput -v 0
 
 echo -n "files "
-./manage.py collectstatic --noinput -v 0 
+./manage.py collectstatic --noinput -v 0
+
+echo -n "awa "
+./manage.py init_awa
 
 echo "complete!"
-popd > /dev/null 2>&1
+popd >/dev/null 2>&1
 
 # autoreload=`setting autoreload
 # sleep 2
